version: "2"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "tail -f /dev/null"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/api
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: sh -c "tail -f /dev/null"
    depends_on:
      - api
    ports:
      - "3001:3001"
    volumes:
      - ./web:/usr/src/web
